import { Link } from "react-router-dom";
import { Zap, Map, Mic2, Users, UserCheck, ArrowRight, Star, CheckCircle } from "lucide-react";

const features = [
  { icon: Map, title: "AI Career Roadmap", desc: "Get a personalized week-by-week career plan generated by GPT-4o-mini based on your skills, degree, and goals.", badge: "GPT-4o" },
  { icon: Mic2, title: "Mock Interview Bot", desc: "Practice real interviews with an AI that gives instant feedback, scores your answers, and helps you improve.", badge: "AI" },
  { icon: UserCheck, title: "Expert Mentors", desc: "Connect with professionals from top companies who've been where you want to go.", badge: "Real People" },
  { icon: Users, title: "Peer Community", desc: "Post questions, share wins, find resources, and grow together with thousands of students.", badge: "Community" },
];

const stats = [
  { value: "10,000+", label: "Real Problems Identified", sub: "by Razorpay Fix My Itch" },
  { value: "#9", label: "Top Problem in India", sub: "career guidance gap" },
  { value: "50K+", label: "People Verified This", sub: "it's a real crisis" },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-dark-900 text-text-primary overflow-hidden">
      {/* Nav */}
      <nav className="border-b border-dark-500 px-6 py-4">
        <div className="max-w-6xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-brand-500 rounded-lg flex items-center justify-center">
              <Zap size={16} className="text-dark-900" />
            </div>
            <span className="font-display text-lg font-semibold">MentorMap</span>
          </div>
          <div className="flex items-center gap-3">
            <Link to="/login" className="btn-ghost text-sm">Sign in</Link>
            <Link to="/register" className="btn-primary text-sm">Get Started <ArrowRight size={15} /></Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="relative px-6 pt-20 pb-16 text-center dot-grid">
        <div className="absolute inset-0 bg-gradient-to-b from-transparent via-dark-900/50 to-dark-900 pointer-events-none" />
        <div className="relative max-w-4xl mx-auto animate-fade-in">
          <div className="inline-flex items-center gap-2 badge-green mb-6 text-sm">
            <Star size={12} />
            Solving India's #9 Problem — Razorpay Fix My Itch
          </div>
          <h1 className="font-display text-5xl md:text-7xl font-bold mb-6 leading-tight">
            Your career path,{" "}
            <span className="gradient-text">mapped by AI.</span>
          </h1>
          <p className="text-text-secondary text-lg md:text-xl max-w-2xl mx-auto mb-10 leading-relaxed">
            Leaving college with no idea what to do next? MentorMap gives you a personalized roadmap, AI mock interviews, and real mentors — everything you need to land your first job.
          </p>
          <div className="flex items-center justify-center gap-4 flex-wrap">
            <Link to="/register" className="btn-primary text-base px-7 py-3">
              Start for Free <ArrowRight size={17} />
            </Link>
            <Link to="/login" className="btn-secondary text-base px-7 py-3">
              Sign in
            </Link>
          </div>
          <p className="text-text-muted text-sm mt-5">No credit card required · Built for Indian students</p>
        </div>
      </section>

      {/* Stats */}
      <section className="px-6 py-12 border-y border-dark-500 bg-dark-800/50">
        <div className="max-w-4xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-8 text-center">
          {stats.map((s) => (
            <div key={s.label} className="animate-slide-up">
              <div className="font-display text-4xl font-bold text-brand-400 mb-1">{s.value}</div>
              <div className="font-medium text-text-primary mb-1">{s.label}</div>
              <div className="text-xs text-text-muted">{s.sub}</div>
            </div>
          ))}
        </div>
      </section>

      {/* Features */}
      <section className="px-6 py-20">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="font-display text-4xl font-bold mb-4">Everything you need to <span className="gradient-text">get hired</span></h2>
            <p className="text-text-secondary text-lg">Four tools. One platform. Your career transformation.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            {features.map(({ icon: Icon, title, desc, badge }) => (
              <div key={title} className="card p-6 hover:border-brand-500/40 transition-all duration-300 group">
                <div className="flex items-start gap-4">
                  <div className="w-11 h-11 rounded-xl bg-brand-500/10 border border-brand-500/20 flex items-center justify-center flex-shrink-0 group-hover:bg-brand-500/20 transition-colors">
                    <Icon size={20} className="text-brand-400" />
                  </div>
                  <div>
                    <div className="flex items-center gap-2 mb-2">
                      <h3 className="font-display text-lg font-semibold">{title}</h3>
                      <span className="badge-green text-xs">{badge}</span>
                    </div>
                    <p className="text-text-secondary text-sm leading-relaxed">{desc}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="px-6 py-16 bg-dark-800/50 border-t border-dark-500">
        <div className="max-w-2xl mx-auto text-center">
          <h2 className="font-display text-3xl font-bold mb-4">Ready to map your career?</h2>
          <p className="text-text-secondary mb-8">Join thousands of students who stopped guessing and started growing.</p>
          <Link to="/register" className="btn-primary text-base px-8 py-3 inline-flex">
            Create Free Account <ArrowRight size={17} />
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-dark-500 px-6 py-6 text-center text-text-muted text-sm">
        <p>MentorMap — Built to solve India's career guidance crisis · Inspired by Razorpay Fix My Itch</p>
      </footer>
    </div>
  );
}